services:
  ml_framework:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "9090:9090"
    networks:
      - shared

networks:
  shared:
    driver: bridge
